# Generated by Django 4.2.19 on 2025-03-06 05:45

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=mptt.fields.TreeForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='blog.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
