# Generated by Django 4.2.19 on 2025-04-05 13:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modules.blog.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_full_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='articles/files/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'pdf')), modules.blog.models.validate_file_size], verbose_name='Файл')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название файла')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='blog.article')),
            ],
            options={
                'verbose_name': 'Файл статьи',
                'verbose_name_plural': 'Файлы статей',
                'ordering': ['-created_at'],
            },
        ),
    ]
